### ISSUE TITLE
Change the nameservers of fossunited.org to digitalocean

### ISSUE THREAD

**Issue by anandology** [fossunited/infra#4]
Please change the nameservers of fossunited.org domain to  the following:

```
ns1.digitalocean.com
ns2.digitalocean.com
ns3.digitalocean.com
```

Digital ocean DNS is very easy to use and anyone with access to the digitalocean console can access it. 

I've already added the following records from whatever I could find with dig.

```
@ | A | 68.183.89.27
www | CNAME | fossunited.frappe.cloud.
```

And `TXT` records for google site verification and MX records for gsuite.

**Comment by anandology** [comment]
Required for #3.

**Comment by abhishekbalam** [comment]
@anandology 
Done 👍

**Comment by anandology** [comment]
Thanks @abhishekbalam.
